### PR TITLE
[Mobile] Profile page missing fields and backend connection

### PR DESCRIPTION
**Pull request by erkamkavak**
Following changes are made in this pr: 
- tags and visibility added to user model
- follow, unfollow and get followings service connections made
- liked, disliked and created post data connections corrected
- tag, visibility and information sections added to profile
- follow section problems corrected in profile

### CODE REVIEW

**Comment by erkamkavak** [comment]
There was a little error on user model(tags are being null) which @smelihportakal mentioned. I fixed it with the last commit.

**Comment by smelihportakal** [comment]
All user functionality work. There is a Visibility button when button is red other user can see the profil page. When button is white other user cannot see the profil page. Button color cannot be understanded by users. If there will be also a text that implies user visibility it will be good.

**Comment by smelihportakal** [comment]
> All user functionality work. There is a Visibility button when button is red other user can see the profil page. When button is white other user cannot see the profil page. Button color cannot be understanded by users. If there will be also a text that implies user visibility it will be good.

Actually there is, but that text does not appear in the emulator I use because it does not fit into the button.

**Comment by erkamkavak** [comment]
> > All user functionality work. There is a Visibility button when button is red other user can see the profil page. When button is white other user cannot see the profil page. Button color cannot be understanded by users. If there will be also a text that implies user visibility it will be good.
> 
> Actually there is, but that text does not appear in the emulator I use because it does not fit into the button.

Thanks for the correction. I increased the size of button. It should work now. Can you check again?

**Comment by umutdmr** [comment]
I am checking @erkamkavak

**Comment by umutdmr** [comment]
Screenshot 2023-12-24 at 14 25 58

I got this problem when i want to go my profile page. What are the possible issues related to this problem? @erkamkavak

**Comment by erkamkavak** [comment]
> Screenshot 2023-12-24 at 14 25 58
> I got this problem when i want to go my profile page. What are the possible issues related to this problem? @erkamkavak

This occurs when you change your profile visibility and other users try to enter your profile page. Two questions: 
- Did you change you profile visibility?
- Did this error occur when you try to enter your own profile?
If yes and no, then there is no problem with this error message

**Comment by umutdmr** [comment]
I tested again, it is working. Good job!

**Pull request merged**
