### PR TITLE
[Mobile] Lfg comment section

### PR DESCRIPTION
**Pull request by erkamkavak**
Following changes are made in this pr: 

- PostState converted to ContentState for use in lfg page
- lfg model updated to be extended from Content model
- lfg comment section made similar to post page comment section

### CODE REVIEW

**Comment by umutdmr** [comment]
I found two issues related to this task:
- A user can upvote and downvote the same comment at the same time.
- Reply section can't be open.

If you worked with mock data, then it is completed.

**Comment by erkamkavak** [comment]
> I found two issues related to this task:
> 
> * A user can upvote and downvote the same comment at the same time.
> * Reply section can't be open.
> 
> If you worked with mock data, then it is completed.

I solved the second problem, thanks for the correction. For the first problem, it was the same for post page; maybe we can fix this if we have time later.

**Comment by umutdmr** [comment]
I wrote a comment as "deneme", then reply this comment. Here is the results:
Screenshot 2023-12-23 at 20 41 05

here is the looking:
Screenshot 2023-12-23 at 20 41 28

this looks wrong, it has to be fixed.

**Comment by erkamkavak** [comment]
> I wrote a comment as "deneme", then reply this comment. Here is the results: Screenshot 2023-12-23 at 20 41 05
> 
> here is the looking: Screenshot 2023-12-23 at 20 41 28
> 
> this looks wrong, it has to be fixed.

This is because backend connections for lfg are not completed yet. Creating comment for lfg is not supported yet and this error is related to this.

**Comment by ohbahadiroglu** [comment]
> > I wrote a comment as "deneme", then reply this comment. Here is the results: Screenshot 2023-12-23 at 20 41 05
> > here is the looking: Screenshot 2023-12-23 at 20 41 28
> > this looks wrong, it has to be fixed.
> 
> This is because backend connections for lfg are not completed yet. Creating comment for lfg is not supported yet and this error is related to this.

backend for lfg section implemented yesterday. now you can solve those issues.

**Comment by umutdmr** [comment]
I am testing @ohbahadiroglu

**Comment by umutdmr** [comment]
There is again the same issue, but if it is related to the backend, then it is done.

**Comment by umutdmr** [comment]
There is another issue, when i close the lfg page after commenting, if i go to the same lfg page again the comment is disappeared.

**Comment by erkamkavak** [comment]
> There is again the same issue, but if it is related to the backend, then it is done. @erkamkavak

No actually it is not related to backend. I haven't done the backend connections yet, I will do them in a different pr. We can close this if there is no issue on the view of the page.

**Comment by umutdmr** [comment]
Okay, if you using mock data right now, then this pr is done. Good job!

**Pull request merged**
