### PR TITLE
Backend/enhancement/implement recommendation service #567

### PR DESCRIPTION
**Pull request by Legervad**
This merge references the #567

### CODE REVIEW

**Comment by ohbahadiroglu** [comment]
@Legervad can you please resolve conflicts ?

**Review by ohbahadiroglu — APPROVED** [review]
thanks for your effort. works fine.

**Comment by Legervad** [comment]
@ohbahadiroglu could you please check the request again?

**Comment by ohbahadiroglu** [comment]
I checked and works fine. thanks.

**Pull request merged**
